# Function to check wheter a required package is loaded or not, if not, then is loaded#################################################
necessaryPkg <- function(packages){
  for (i in packages){
    if(!(i %in% .packages())){
      library(i,character.only = TRUE)
    }
  }
}

# Function to take a data frame with valuations from a long period of time and generate historical data up to the last complete month##
Historico <- function(baseValuaciones, porOficina){
  
  # Importing necessary libraries
  necessaryPkg(c("lubridate","data.table","tidyverse"))
  
  # Verifying that column type are correct-----------------------------------------------------------------------------
  # Firstly it is necessary to set FechaOcurrido and FechaAutorizacionValuacion to date because they have innecesary time stamps
  baseValuaciones$FechaOcurrido <- as.Date(baseValuaciones$FechaOcurrido)#,format="%d-%m-%Y")#Converting to date
  baseValuaciones$FechaAutorizacionValuacion <- as.Date(baseValuaciones$FechaAutorizacionValuacion)#,format="%d-%m-%Y")#Converting to date
  
  actualColumnsType <- unlist(lapply(baseValuaciones,class))#Getting the column type that was read from csv
  mustColumnsType <- c("factor","factor","factor","Date","Date","numeric","numeric","numeric","numeric","integer","factor","factor","integer","factor")#Required column type
  
  idx <- actualColumnsType == mustColumnsType#Which columns don't match the correct type
  
  names(idx[idx == FALSE])
  
  # Factors
  baseValuaciones$ValLst_NumeroExpediente <- as.factor(baseValuaciones$ValLst_NumeroExpediente)
  baseValuaciones$Asegurado_Tercero <- as.factor(baseValuaciones$Asegurado_Tercero)
  baseValuaciones$IdOficinaAtencion <- as.factor(baseValuaciones$IdOficinaAtencion)
  baseValuaciones$MarcaVehiculoNormalizado <- as.factor(baseValuaciones$MarcaVehiculoNormalizado)
  baseValuaciones$SubMarcaVehiculo <- as.factor(baseValuaciones$SubMarcaVehiculo)
  baseValuaciones$Modelo <- as.integer(baseValuaciones$Modelo)
  baseValuaciones$TipoCentroReparacion <- as.factor(baseValuaciones$TipoCentroReparacion)
  
  # Ordering data by date. FechaAutorizacionValuacion
  baseValuaciones <- dplyr::arrange(baseValuaciones,FechaAutorizacionValuacion)
  rangoFechas <- seq(min(baseValuaciones$FechaAutorizacionValuacion),by ="month",length.out = elapsed_months(max(baseValuaciones$FechaAutorizacionValuacion),min(baseValuaciones$FechaAutorizacionValuacion)))
  
  # Generating historic data-----------------------------------------------------------------------------
  datosMensuales = list()
  for (i in 1:length(rangoFechas)){
    if(i < length(rangoFechas)){
      datosMensuales[[i]] = subset(baseValuaciones,FechaAutorizacionValuacion >= rangoFechas[i] & FechaAutorizacionValuacion < rangoFechas[i+1])
    }
    else{
      datosMensuales[[i]] = subset(baseValuaciones,FechaAutorizacionValuacion >= rangoFechas[i] & FechaAutorizacionValuacion < rangoFechas[i]+months(1)-days(1))
    }
  }
  
  # Getting the number of valuations, mean pieces per valuation, mean cost per piece and total replacement expenses per month
  valuationsPerMonth <- sapply(datosMensuales, dim)[1,]#Counting the number of valuations per month
  meanPiecesPerValuation = numeric()#declaring empty numeric array for the average of replacements per valuation
  meanCostPerPiece = numeric()# Declaring empty numeric array for mean cost per replacement
  monthlyWorkForce = numeric()# Declaring empty numeric array for monthly workforce cost
  
  for (i in 1:length(valuationsPerMonth)){
    meanPiecesPerValuation[i] <- mean(datosMensuales[[i]]$NumeroTotalPiezas)#Mean pieces per valuation
    meanCostPerPiece[i] <-sum(datosMensuales[[i]]$MontoRefacciones)/sum(datosMensuales[[i]]$NumeroTotalPiezas)#Mean cost per piece
    monthlyWorkForce[i] <- sum(datosMensuales[[i]]$MontoManoObra)# Mean cost of the workforce
  }
  totalReplacementExpenses <- valuationsPerMonth*meanCostPerPiece*meanPiecesPerValuation
  
  # Generating data frame to feed the model
  if(porOficina == TRUE){#If the historical data is generated by office
    historico <- data.frame(rangoFechas, rep(baseValuaciones$IdOficinaAtencion[1],length(valuationsPerMonth)),valuationsPerMonth, meanCostPerPiece, meanPiecesPerValuation, monthlyWorkForce/valuationsPerMonth)
    names(historico) <- c("Fecha","IdOficina", "NumeroDeValuaciones","CostoPromedioPorPieza","NumeroPiezasPorValuacion","MontoManoObraPromedio")
  }
  else{
  historico <- data.frame(rangoFechas, valuationsPerMonth, meanCostPerPiece, meanPiecesPerValuation, monthlyWorkForce/valuationsPerMonth)
  names(historico) <- c("Fecha", "NumeroDeValuaciones","CostoPromedioPorPieza","NumeroPiezasPorValuacion","MontoManoObraPromedio")
  }
  if(porOficina == TRUE){
    return(historico)
  }
  else{
    return(list(baseValuaciones,historico))
  }
  
}

# This function calculates the number of months elapsed between two dates
elapsed_months <- function(end_date,start_date){
  12*(year(end_date) - year(start_date)) + (month(end_date) -month(start_date))
}
# This function takes a data frame with vehicles Year and finds the five time intervals to split them##################################
rango_modelos <- function(baseDatos){
  rangoModelo <- c(as.integer(format(Sys.Date(),"%Y"))
                   , as.integer(format(Sys.Date(),"%Y"))-c(2,4,6,7))#Time intervals to group different vehicle models
  names(rangoModelo) <- c(as.character(rangoModelo[1])
                          , paste(as.character(rangoModelo[1]-1),"-",as.character(rangoModelo[2]), sep = "")
                          , paste(as.character(rangoModelo[2]-1),"-",as.character(rangoModelo[3]), sep = "")
                          , paste(as.character(rangoModelo[3]-1),"-",as.character(rangoModelo[4]), sep = "")
                          , paste("<=",as.character(rangoModelo[5]), sep = ""))
}

# Function to clean up a data frame removing those rows with values that make no sense#################################################
basic_clean <- function(baseDatos){
  library(dplyr)
  baseDatos %>%
    filter(ValorComercial > 0 & NumeroTotalPiezas > 0 &  MontoRefacciones >= 0 & MontoTotalValuacion > 0 & Modelo <= as.integer(format(Sys.Date(),"%Y")) & Modelo >= 1886)
}

# This function separates a dataframe by vehicle's Modelo generating ##################################################################
Antiguedad <- function(tmp,rango){
  
  antig = list()#List to save dataframes of vehicles by Modelo
  for (j in 1:length(rango)){#For loop to iterate over the vehicle Model
    
    if(j == 1){
      antig[[j]] <- subset(tmp, Modelo == rango[j])#Last year model
    }
    
    else if(j == length(rango)){
      antig[[j]] <- subset(tmp, Modelo <= rango[j])
    }
    
    else{
      antig[[j]] <- subset(tmp, Modelo < rango[j-1] & Modelo >= rango[j])
    }
    
  }
  return(antig)
}

# Function to check performance of ARIMA model#########################################################################################

farima <- function(x, h) {
  forecast(auto.arima(x, stepwise = FALSE), h=h)
}

# Function to check performance of ETS model##########################################################################################
fets <- function(x, h){
  forecast(ets(x), h = h)
}

# Function to check performance of Holt-Winters model#################################################################################
fhw <- function(x, h){
  forecast(hw(x), h = h)
}

# Function to perform forecast of the best model (based on MSE calculated in the main script)#########################################
bestModel <- function(MSE,serie, meses){
  best = names(which(MSE == min(MSE)))
  if(best == "ETS"){
    fc <- forecast(ets(serie), h = meses)
  } else if(best == "ARIMA"){
    fc <- forecast(auto.arima(serie, stepwise = FALSE), h = meses)
  } else if (best == "Holt-Winters"){
    fc <- forecast(hw(serie), h = meses)
  } else{
    print("This function only can test three models: ETS, ARIMA and Holt-Winters")
  }
}

# Funcion to take a data frame with valuations from all the company and split it by valuations per office#############################
separarOficinas <- function(file, baseDatos){
  necessaryPkg('rlist')
  oficinas <- read.csvoficinas <- read.csv(file, stringsAsFactors = FALSE, colClasses = c("NULL","factor", "factor", "character"))
  
  listaOficina = list()
  nombres = list()
# Grouping data by IdOficinaAtencion----------------------------
  agrupados  <- baseDatos %>% group_split(IdOficinaAtencion)
# Getting rid of the data belonging to offices with just a few sinisters per year----------------------------
  for(i in seq(1,length(agrupados))){
    if(dim(agrupados[[i]])[1] >= 300){
      listaOficina = list.append(listaOficina,agrupados[[i]] %>% as.data.frame())
      nombres = list.append(nombres,as.character(agrupados[[i]]$IdOficinaAtencion[1]))
                                    }
  }
  names(listaOficina) <- nombres
  return(list(listaOficina, oficinas))
}
# Funcion to generate forecasting for replacements, valuations and replacement's cost)################################################
predictReplacements <- function(historico, meses){
  
  necessaryPkg(c("forecast","ggplot2","MASS","tidyverse","ggpubr","broom","AICcmodavg"))
  
  tsValuaciones <- ts(historico$NumeroDeValuaciones
                      , frequency = 12
                      , start = c(as.integer(format(historico[1,1],"%Y")),as.integer(format(historico[1,1],"%m"))))
  tsCostoPieza <- ts(historico$CostoPromedioPorPieza
                     , frequency = 12
                     , start = c(as.integer(format(historico[1,1],"%Y")),as.integer(format(historico[1,1],"%m"))))
  tsManoObra <- ts(historico$MontoManoObraPromedio
                     , frequency = 12
                     , start = c(as.integer(format(historico[1,1],"%Y")),as.integer(format(historico[1,1],"%m"))))
  tsPiezas <- ts(historico$NumeroPiezasPorValuacion
                 , frequency = 12
                 , start = c(as.integer(format(historico[1,1],"%Y")),as.integer(format(historico[1,1],"%m"))))
  
  # Predicting mean cost per replacement---------------------------------------------------------------------
  
  # Time Series Cross-Validation to check performance of different models
  error1costo <- tsCV(tsCostoPieza, fets, h = meses)
  error2costo <- tsCV(tsCostoPieza, farima, h = meses)
  error3costo <- tsCV(tsCostoPieza, fhw, h = meses)
  
  # Calculating the Mean Square Error for each model to pick the better
  MSEcosto <- c(mean(error1costo^2, na.rm = TRUE),mean(error2costo^2, na.rm = TRUE),mean(error3costo^2, na.rm = TRUE))
  names(MSEcosto) <- c("ETS","ARIMA","Holt-Winters")
  
  fcCosto <- bestModel(MSEcosto, tsCostoPieza, meses)# Selecting the best model and generating forecast
  
  # Predicting replacements per valuation---------------------------------------------------------------------
  
  # Time Series Cross-Validation to check performance of different models
  error1Piezas <- tsCV(tsPiezas, fets, h = meses)
  error2Piezas <- tsCV(tsPiezas, farima, h = meses)
  error3Piezas <- tsCV(tsPiezas, fhw, h = meses)
  
  # Calculating the Mean Square Error for each model to pick the better
  MSEPiezas <- c(mean(error1Piezas^2, na.rm = TRUE),mean(error2Piezas^2, na.rm = TRUE),mean(error3Piezas^2, na.rm = TRUE))
  names(MSEPiezas) <- c("ETS","ARIMA","Holt-Winters")
  
  fcPiezas <- bestModel(MSEPiezas, tsPiezas, meses)# Selecting the best model and generating forecast
  
  #########################
  
  # Predicting mean workforce cost per valuation--------------------------------------------------------------
  
  # Time Series Cross-Validation to check performance of different models
  error1ManoObra <- tsCV(tsManoObra, fets, h = meses)
  error2ManoObra <- tsCV(tsManoObra, farima, h = meses)
  error3ManoObra <- tsCV(tsManoObra, fhw, h = meses)
  
  # Calculating the Mean Square Error for each model to pick the better
  MSEManoObra <- c(mean(error1ManoObra^2, na.rm = TRUE),mean(error2ManoObra^2, na.rm = TRUE),mean(error3ManoObra^2, na.rm = TRUE))
  names(MSEManoObra) <- c("ETS","ARIMA","Holt-Winters")
  
  fcManoObra <- bestModel(MSEManoObra, tsManoObra, meses)# Selecting the best model and generating forecast
  
  # Predicting the number of valuations---------------------------------------------------------------------
  
  modeloVal <- loess(historico$NumeroDeValuaciones~c(1:dim(historico)[1]), control = loess.control(surface = "direct"))
  fcVal <- predict(modeloVal, seq(dim(historico)[1]+1,dim(historico)[1]+elapsed_months('2022-01-01',Sys.Date())), se = TRUE)# Generating the predictions
  
  return(list(fcCosto, fcPiezas, fcVal, fcManoObra))
}
# Funcion to extract dataframe from forecasting objects#################################################################################
extraerPredicciones <- function(FORECAST){
  datosExportar = data.frame()# Creating data frame to export data
    
  if(length(FORECAST) == 4){
    # print(length(FORECAST))
    fcCosto <- FORECAST[[1]]
    fcPiezas <- FORECAST[[2]]
    fcVal <- FORECAST[[3]]
    fcManoObra <- FORECAST[[4]]
    datosExportar <- rbind(datosExportar
                            , cbind(rep(format(Sys.Date(),"%Y"),length(fcCosto$mean))
                                    , rep(format(Sys.Date(),"%m"),length(fcCosto$mean))#-month(1)
                                    , format(as.Date(time(fcCosto$mean)), "%Y%m")
                                    , round(fcCosto$mean)
                                    , round(fcCosto$lower)
                                    , round(fcCosto$upper)
                                    , round(fcPiezas$mean, 2)
                                    , round(fcPiezas$lower, 2)
                                    , round(fcPiezas$upper, 2)
                                    , round(fcManoObra$mean)
                                    , round(fcManoObra$lower)
                                    , round(fcManoObra$upper)
                                    , round(fcVal$fit)
                            ))

    names(datosExportar) <- c("Anio_Prediccion","Mes_Prediccion","Periodo"
                              , "Costo_Prdic", "Costo_inf80", "Costo_inf95", "Costo_sup80", "Costo_sup95"
                              , "Pzas_Predic", "Pzas_inf80",    "Pzas_inf95", "Pzas_sup80", "Pzas_sup95"
                              , "ManoObra_Pred", "ManoObra_inf80", "ManoObra_inf95", "ManoObra_sup80", "ManoObra_sup95", "Valuaciones_Pred")
    
  }
  
  else{
    # print(length(FORECAST))
    for(i in 1:length(FORECAST)){
      fcCosto <- FORECAST[[i]][[1]]
      fcPiezas <- FORECAST[[i]][[2]]
      fcVal <- FORECAST[[i]][[3]]
      fcManoObra <- FORECAST[[i]][[4]]
      datosExportar <- rbind(datosExportar
                              , cbind(rep(format(Sys.Date(),"%Y"),length(fcCosto$mean))
                                      , rep(format(Sys.Date(),"%m"),length(fcCosto$mean))#-months(1)
                                      , format(as.Date(time(fcCosto$mean)), "%Y%m")
                                      , rep(names(FORECAST[i]), length(fcCosto$mean))
                                      , round(fcCosto$mean)
                                      , round(fcCosto$lower)
                                      , round(fcCosto$upper)
                                      , round(fcPiezas$mean, 2)
                                      , round(fcPiezas$lower, 2)
                                      , round(fcPiezas$upper, 2)
                                      , round(fcManoObra$mean)
                                      , round(fcManoObra$lower)
                                      , round(fcManoObra$upper)
                                      , round(fcVal$fit)
                              ))
    }

    names(datosExportar) <- c("Anio_Prediccion","Mes_Prediccion", "Periodo", "IdOficina"
                              , "Costo_Prdic", "Costo_inf80", "Costo_inf95", "Costo_sup80", "Costo_sup95"
                              , "Pzas_Predic", "Pzas_inf80",    "Pzas_inf95", "Pzas_sup80", "Pzas_sup95"
                              , "ManoObra_Pred", "ManoObra_inf80", "ManoObra_inf95", "ManoObra_sup80", "ManoObra_sup95", "Valuaciones_Pred")
    datosExportar$IdOficina <- as.factor(datosExportar$IdOficina)

  }
  
  return(datosExportar)
}
